// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_HafizA.DataAccess;

#nullable disable

namespace Project_HafizA.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project_HafizA.Core.Main", b =>
                {
                    b.Property<int>("Ayet_kodu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ayet_kodu"));

                    b.Property<int>("Ayet_no")
                        .HasColumnType("int");

                    b.Property<string>("Metin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Secde")
                        .HasColumnType("bit");

                    b.Property<int>("Sure_kodu")
                        .HasColumnType("int");

                    b.Property<bool>("Uzun")
                        .HasColumnType("bit");

                    b.HasKey("Ayet_kodu");

                    b.ToTable("Main");
                });
#pragma warning restore 612, 618
        }
    }
}
